version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "51 23 3,18 * *"
    open-pull-requests-limit: 2
    labels:
      - ":robot: AutoSummon"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/packages/node-commitlint"
    schedule:
      interval: "cron"
      cronjob: "51 23 3,18 * *"
    open-pull-requests-limit: 2
    labels:
      - ":robot: AutoSummon"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/packages/python-gitlint"
    schedule:
      interval: "cron"
      cronjob: "51 23 3,18 * *"
    open-pull-requests-limit: 2
    labels:
      - ":robot: AutoSummon"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "51 23 3,18 * *"
    open-pull-requests-limit: 2
    labels:
      - ":robot: AutoSummon"
    groups:
      dependencies:
        patterns:
          - "*"
